### ISSUE TITLE
Documentation: Scrum Methodology

### ISSUE THREAD

**Issue by wycliffepeart** [zendexa/project#7]
## Description

Scrum is an Agile framework used for managing and delivering complex projects, particularly in software development. Scrum teams adhere to a set of principles and practices that define the framework. Here are key attributes and components of Scrum:

## Attributes

| Attribute | Description
| :-------------------- | -- |
| Scrum Roles |- `Product Owner`:  Represents the stakeholders, defines the product backlog, and prioritizes work based on value. <br/> - `Scrum Master`:  Facilitates the Scrum process, removes impediments, and ensures the team adheres to Scrum <br/> - `Development Team`:  is a Self-organizing, cross-functional group responsible for delivering increments of work. |
| Artifacts | `Product Backlog`: - A prioritized list of all desired product features, enhancements, and bug fixes. Managed by the Product Owner. <br/> - `Sprint Backlog`:  A subset of the Product Backlog items selected for the current sprint, committed to by the Development Team. <br/> - `Increment `:  A potentially shippable product increment created by the Development Team during a sprint. |
| Scrum Events | - `Sprint`: The sprint is time-boxed at a period of **2-4 weeks** during which a potentially releasable product increment is developed. <br/> - `Sprint Planning`: This is a meeting at the start of each sprint where the team selects work from the Product Backlog for the sprint backlog. It is timeboxed at **8 hours** for a one-month sprint. For shorter sprints the time is usually shorter. <br/> - `Daily Scrum`: This is a brief daily meeting, timeboxed at **15 minutes**, where the team discusses progress, plans for the day, and identifies impediments. <br/> - `Sprint Review`: This is a meeting at the end of a sprint to review and demonstrate the completed increment to stakeholders. It is timeboxed at **4 hours** for a one-month sprint. For shorter sprints the time is usually shorter. <br/> - `Sprint Retrospective`:  This is a meeting at the end of a sprint, for the team to reflect on their work and identify areas for improvement. It is timeboxed at maximum **3 hours** for a one-month sprint and for shorter sprints the event is usually shorter. | 
| Other Attributes | -`Transparency`: - Scrum emphasizes transparency by making information about work, progress, and challenges visible to all team members and stakeholders. <br/> - `Inspection`: Scrum is an empirical process, and teams regularly inspect the current state of the product, processes, people aspects, practices, and continuous improvements. Inspection can be done by anyone on the Scrum Team or by the stakeholders. Inspection enables feedback and learning, which are essential for innovation and value delivery. The Sprint Review and Sprint Retrospective events facilitate inspection. <br/> - `Adaptation`: Adaptation in scrum means taking action based on the results of inspection. It is about continuous improvement, the ability to adapt based on the changing needs of the customer and the market, which are necessary for discovering new opportunities and solutions. The Sprint review and Sprint Retrospective events facilitate adaptation. <br/> - `Time-Boxing`: Scrum uses time-boxing to limit the duration of events (e.g., sprints) to ensure regular inspection and adaptation. <br/> - `Self-Organization`: Scrum teams are self-organizing, meaning they determine how to complete their work and manage their tasks within the sprint. <br/> - `Empiricism`: Scrum is built on the principles of empiricism, which means decisions are based on observation, experience, and evidence rather than guesswork. <br/> - `Definition of Done (DoD`:  Each increment of work must meet a shared Definition of Done, ensuring that it is of sufficient quality and completeness for release. <br/> - `Continuous Improvement`:  Scrum teams regularly seek ways to improve their processes and work together more effectively. The Sprint Retrospective is a dedicated event for discussing improvements. <br/> - `Customer Focus`:  Scrum prioritizes delivering value to customers and stakeholders through frequent, incremental releases. <br/> - `Flexibility`: Scrum accommodates changing requirements and priorities by allowing the Product Owner to adjust the product backlog. <br/> - `Roles Collaboration`:  Collaboration and communication among the Product Owner, Scrum Master, and Development Team are essential to the framework's success. |

Scrum is a highly adaptable framework and is used not only in software development but also in various other industries for managing complex projects. Its attributes promote agility, collaboration, and customer-centricity, making it a popular choice for teams and organizations seeking to improve their project management practices.

**Comment by iamshellyan** [comment]
@wycliffepeart i made some changes to Inspection and adaptation, separated them

**Comment by wycliffepeart** [comment]
> @wycliffepeart i made some changes to Inspection and adaptation, separated them

@iamshellyan Perfect 👌

**Comment by wycliffepeart** [comment]
@iamshellyan This story needs to be refined some more, for instance, the grouping is not the best I think we could go with something like:

### Current Implementation 

**Roles:**

| Attribute | Description
| :-------------------- | -- |
| Product Owner | Represents the stakeholders, defines the product backlog, and prioritizes work based on value. |
| Scrum Master | Facilitates the Scrum process, removes impediments, and ensures the team adheres to Scrum principles. |
| Development Team | Self-organizing, cross-functional group responsible for delivering increments of work. |

### Suggested Implementation 

| Attribute | Description |
| :-------------------- | -- |
| Roles | - `Product Owner`, Represents the stakeholders, defines the product backlog, and prioritizes work based on value. <br/> -  `Scrum Master`, Facilitates the Scrum process, removes impediments, and ensures the team adheres to Scrum principles. <br/> - `Development Team`, Self-organizing, the cross-functional group responsible for delivering increments of work. |

I think the second option utilizes less space and is more consistent with our workflow.

**Comment by wycliffepeart** [comment]
@iamshellyan Hi

**Comment by wycliffepeart** [comment]
@iamshellyan
